description = "Tiny base image (bionic build image, distroless-like run image) with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.16.0"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.3.111-tiny-cnb"
  id = "io.paketo.stacks.tiny"
  run-image = "index.docker.io/paketobuildpacks/run:tiny-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:tiny-cnb"]
